trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONARQUBE_PROJECT_KEY: 'test'
  SONARQUBE_PROJECT_NAME: 'test'
  SONARQUBE_PROJECT_VERSION: '1.0'
  SONARQUBE_SERVICE_CONNECTION: 'Sonar-Qube'
  BUILD_SOURCESDIRECTORY: $(Build.SourcesDirectory)

stages:
- stage: 'SonarQubeAnalysis'
  displayName: 'SonarQube Analysis'
  jobs:
  - job: 'Analyze'
    displayName: 'Analyze'
- stage: Build
  displayName: Image Build
  jobs:
  - job: Build
    displayName: Build and Push the image to ACR
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'cai-yaml-test'
        repository: 'test'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
- stage: Test
  displayName: trivy test
  dependsOn:
  - Build
  condition: succeeded()
  jobs:
  - job: test_with_trivy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'cai-yaml-test'
        command: 'login'
    - task: trivy@1
      inputs:
        version: 'latest'
        loginDockerConfig: true
        image: 'conversationalai.azurecr.io/test:$(Build.BuildId)'
        severities: 'CRITICAL,HIGH'
        exitCode: '0'
- stage: DependencyCheck
  jobs:
  - job: OWASPDependencyCheck
    steps:
    - script: |
        echo Installing OWASP Dependency Check...
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.1.6/dependency-check-6.1.6-release.zip
        unzip dependency-check-6.1.6-release.zip
      displayName: 'Install OWASP Dependency Check'

    - script: |
        echo Running OWASP Dependency Check...
        ./dependency-check/bin/dependency-check.sh --project "YourProjectName" --scan "$(Build.SourcesDirectory)/" --out "$(Build.ArtifactStagingDirectory)/dependency-check-report"
      displayName: 'Run OWASP Dependency Check'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/dependency-check-report'
        artifact: 'OWASPDependencyCheckReport'
 