trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONARQUBE_PROJECT_KEY: 'test'
  SONARQUBE_PROJECT_NAME: 'test'
  SONARQUBE_PROJECT_VERSION: '1.0'
  SONARQUBE_SERVICE_CONNECTION: 'SonarQubeServiceConnection'
  BUILD_SOURCESDIRECTORY: $(Build.SourcesDirectory)

stages:
- stage: 'SonarQubeAnalysis'
  displayName: 'SonarQube Analysis'
  jobs:
  - job: 'Analyze'
    displayName: 'Analyze'
