trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONARQUBE_PROJECT_KEY: 'test'
  SONARQUBE_PROJECT_NAME: 'test'
  SONARQUBE_PROJECT_VERSION: '1.0'
  SONARQUBE_SERVICE_CONNECTION: 'SonarQube'
  BUILD_SOURCESDIRECTORY: $(Build.SourcesDirectory)
  DEPENDENCY_CHECK_VERSION: '6.3.2' # Update to the desired version

stages:
- stage: 'SonarQubeAnalysis'
  displayName: 'SonarQube Analysis'
  jobs:
  - job: 'Analyze'
    displayName: 'Analyze'
- stage: Build
  displayName: Image Build
  jobs:
  - job: Build
    displayName: Build and Push the image to ACR
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'cai-yaml-test'
        repository: 'test'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

- stage: DependencyCheck
  displayName: OWASP Dependency Check
  dependsOn:
  - Build
  condition: succeeded()
  jobs:
  - job: dependency_check
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        wget https://github.com/jeremydmiller/aspnetboilerplate/releases/download/dependency-check-${{ variables.DEPENDENCY_CHECK_VERSION }}/dependency-check-${{ variables.DEPENDENCY_CHECK_VERSION }}-release.zip
        unzip dependency-check-${{ variables.DEPENDENCY_CHECK_VERSION }}-release.zip
        dependency-check/bin/dependency-check.sh --project "My Project" --scan $(BUILD_SOURCESDIRECTORY) --format "ALL" --out $(Build.ArtifactStagingDirectory)/dependency-check
      displayName: 'Run OWASP Dependency Check'

- stage: Test
  displayName: Trivy Test
  dependsOn:
  - Build
  condition: succeeded()
  jobs:
  - job: test_with_trivy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'cai-yaml-test'
        command: 'login'
    - task: trivy@1
      inputs:
        version: 'latest'
        loginDockerConfig: true
        image: 'conversationalai.azurecr.io/test:$(Build.BuildId)'
        severities: 'CRITICAL,HIGH'
        exitCode: '1' # Adjust based on desired behavior

