trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Define variables to store the commit ID and tag
  commitId: ''
  tag: ''

steps:
- script: |
    # Fetch the latest tags
    git fetch --tags
    
    # Get the commit ID
    commitId=$(git rev-parse HEAD)
    echo "Commit ID: $commitId"
    
    # Get the date of the commit
    commitDate=$(git show -s --format=%ci $commitId)
    echo "Commit Date: $commitDate"
    
    # Get the latest tag associated with the commit
    tag=$(git describe --tags $commitId)
    echo "Tag: $tag"
    
    # Set the variables for further use in the pipeline
    echo "##vso[task.setvariable variable=commitId]$commitId"
    echo "##vso[task.setvariable variable=commitDate]$commitDate"
    echo "##vso[task.setvariable variable=tag]$tag"
  displayName: 'Get Commit Date and Tag'

# You can add more steps here to use the variables

- script: |
    echo "Commit ID: $(commitId)"
    echo "Commit Date: $(commitDate)"
    echo "Tag: $(tag)"
  displayName: 'Display Commit Information'



        

