trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONARQUBE_PROJECT_KEY: 'test'
  SONARQUBE_PROJECT_NAME: 'test'
  SONARQUBE_PROJECT_VERSION: '1.0'
  SONARQUBE_SERVICE_CONNECTION: 'Sonar-Qube'
  BUILD_SOURCESDIRECTORY: $(Build.SourcesDirectory)

stages:
- stage: 'SonarQubeAnalysis'
  displayName: 'SonarQube Analysis'
  jobs:
  - job: 'Analyze'
    displayName: 'Analyze'
- stage: Build
  displayName: Image Build
  jobs:
  - job: Build
    displayName: Build and Push the image to ACR
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'cai-yaml-test'
        repository: 'test'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
- stage: Test
  displayName: trivy test
  dependsOn:
  - Build
  condition: succeeded()
  jobs:
  - job: test_with_trivy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'cai-yaml-test'
        command: 'login'
    - task: trivy@1
      inputs:
        version: 'latest'
        loginDockerConfig: true
        image: 'conversationalai.azurecr.io/test:$(Build.BuildId)'
        severities: 'CRITICAL,HIGH'
        exitCode: '0'
 