# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 paths:
   include:
     - worker/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        Dockerfile: 'worker/Dockerfile'
        tags: '$(tag)'
variables:
  GIT_COMMIT: $(Build.SourceVersion) # <- How can I get the checked out Commit ID for the MyBitBucketRepo?
  GIT_BRANCH: $(Build.SourceBranchName) # And the branch name?

steps:
- checkout: vooting-app

- script: dir $(Build.SourcesDirectory)
- script: echo $(GIT_COMMIT)
- script: echo $(GIT_BRANCH)

steps:
- bash: |
   # Write your commands here
   
   # Get the build tag based on the date
   buildtag=$(date +'%Y.%m.%d')
   echo "Build Tag: $buildtag"
   
   version=$(git rev-parse --short=8 HEAD)
   echo "Version ID: $version"
   
   # Add the '-' prefix to the version number
   version_with_prefix="-$version"
   echo "Version with Prefix: $version_with_prefix"
   
   # Append the version ID to the build tag
   buildtagwithversion="$buildtag$version_with_prefix"
   echo "Build Tag with Version: $buildtagwithversion"
   
   # Set the build tag with version as a variable
   echo "##vso[task.setvariable variable=build-tag-with-version;]$buildtagwithversion"
   
   
  displayName: 'Bash Script'

- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: 'sumedh03'
    repository: 'sumedh1991'
    tags: '$(build-tag-with-version)'
