trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
variables:
  BUILD_SOURCESDIRECTORY: $(Build.SourcesDirectory)
stages:
- stage: Build
  displayName: Image Build
  jobs:
  - job: Build
    displayName: Build and Push the image to ACR
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'cai-yaml-test'
        repository: 'test'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
- stage: DependencyCheck
  displayName: OWASP Dependency Check
  dependsOn:
  - Build
  condition: succeeded()
  jobs:
  - job: dependency_check
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        # Install .NET SDK
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-6.0
        
        # Download and unzip OWASP Dependency Check
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v${{ variables.DEPENDENCY_CHECK_VERSION }}/dependency-check-${{ variables.DEPENDENCY_CHECK_VERSION }}-release.zip
        unzip dependency-check-${{ variables.DEPENDENCY_CHECK_VERSION }}-release.zip -d dependency-check
        
        # Run OWASP Dependency Check with enhanced logging
        dependency-check/bin/dependency-check.sh \
          --project "My Project" \
          --scan $(BUILD_SOURCESDIRECTORY) \
          --format "ALL" \
          --out $(Build.ArtifactStagingDirectory)/dependency-check \
          --log $(Build.ArtifactStagingDirectory)/dependency-check/dependency-check.log
      displayName: 'Run OWASP Dependency Check'